openapi: 3.0.0
info:
  title: Balder Service API
  version: 1.0.0
  description: API documentation for the Balder service
servers:
  - url: http://localhost:3002
    description: Local development server
  - url: http://balder:3002
    description: Docker service
paths:
  /api/tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    title:
                      type: string
                    description:
                      type: string
                    status:
                      type: string
                      enum: [OPEN, IN_PROGRESS, COMPLETED]
                    createdAt:
                      type: string
                      format: date-time
                    updatedAt:
                      type: string
                      format: date-time
        '500':
          description: Server error
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
              required:
                - title
      responses:
        '201':
          description: Task created successfully
        '500':
          description: Server error
  /api/tasks/{id}:
    delete:
      summary: Delete a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
        '500':
          description: Server error
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Service health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
                  uptime:
                    type: number
  /version:
    get:
      summary: Get service version
      responses:
        '200':
          description: Service version information
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                  service:
                    type: string
                  environment:
                    type: string 