version: '3.8'

services:
  api-test:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@db-test:5432/api_test
    depends_on:
      - db-test
    command: npm run test

  db-test:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data: 