version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=development
      - PORT=8090
      - CORS_ORIGINS=http://localhost:8090
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3 