global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nestjs'
    metrics_path: '/v1/metrics'
    static_configs:
      - targets: ['api:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'avetta-doc-agent'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['avetta-doc-agent:3000'] 