global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'

  - job_name: 'document-service'
    static_configs:
      - targets: ['document-service:3001']
    metrics_path: '/metrics'

  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:3002']
    metrics_path: '/metrics'

  - job_name: 'webhook-service'
    static_configs:
      - targets: ['webhook-service:3003']
    metrics_path: '/metrics'

  - job_name: 'monitoring-service'
    static_configs:
      - targets: ['monitoring-service:3004']
    metrics_path: '/metrics'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

rule_files:
  - 'rules/*.yml' 