version: '3.8'

services:
  brokkr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - PORT=3007
      - HEL_DB_HOST=postgres
      - HEL_DB_PORT=5432
      - HEL_DB_USERNAME=postgres
      - HEL_DB_PASSWORD=postgres
      - HEL_DB_DATABASE=hel
      - BIFROST_URL=http://bifrost:3001
      - TASK_SERVICE_URL=http://task-service:3000
      - UI_SERVICE_URL=http://ui-service:3002
    depends_on:
      - postgres
    networks:
      - microservices-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hel
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

volumes:
  postgres-data:

networks:
  microservices-network:
    driver: bridge 