version: '3.8'

services:
  document-service:
    build: .
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=documents
    depends_on:
      - postgres
    networks:
      - document-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=documents
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - document-network

networks:
  document-network:
    driver: bridge

volumes:
  postgres-data: 